### ISSUE TITLE
Add option to omit members

### ISSUE THREAD

**Issue by amadare42** [RafaelSalguero/CSharp2TS#12]
Since most popular use-case of the extension is to just convert DTOs, I think it can be useful to omit some members on the conversion like private/internal members, methods, simple backing field properties. I don't really think it is good to place all these things into DTO in the first place, but I'm sure that this will have some use-cases.

**Comment by RafaelSalguero** [comment]
What would be the conditions to omit members? Maybe "Omit private members", "Omit internal members" and "Omit members starting with _"

**Comment by amadare42** [comment]
All useful omit options that I can think of:

1. Members with names that match specified regexes
2. Private members
3. Internal members
4. Constructors

But of course, it should just be options and I don't think any of it should be enabled by default.

**Comment by RafaelSalguero** [comment]
Constructor removal should be working, can be enabled with the `removeConstructors` option, I'll add the options for the other 3 cases

**Comment by RafaelSalguero** [comment]
Closed with commit c07489aa9006c66059a9111173953e10232759f7 and version 0.0.22
