### ISSUE TITLE
Additional options for configuring the conversion

### ISSUE THREAD

**Issue by pfeigl** [RafaelSalguero/CSharp2TS#13]
Hi there, just wanted to say "thanks" for the plugin which works nicely and wanted to propse some additional options for configuring the plugin:

1. classes are currently always mapped to interfaces. It would be nice to be able to configure to generate a class instead of an interface
2. modifiers are always removed from public properties. We setup our tslint options to have them as required, so it would be nice to be able to generate them into the result.

**Comment by RafaelSalguero** [comment]
Adding this options to the configurations. Thanks for your suggestions!

**Comment by RafaelSalguero** [comment]
Closed with commit c07489aa9006c66059a9111173953e10232759f7 and version 0.0.22

**Comment by pfeigl** [comment]
Wow, hat feedback time was impressive! Already installed the update and it just works as expected. Thanks 👍
