### ISSUE TITLE
Convert C# to TS when pasting code

### ISSUE THREAD

**Issue by labarilem** [RafaelSalguero/CSharp2TS#15]
Hi,

I'd find very useful a command which converts to TypeScript the C# code copied in the clipboard and then pastes it at the cursor's position in the editor.
Having a keyboard schortcut for this command would make it quick to convert & paste C# code from another editor.

Would you accept a PR for this feature?

**Comment by RafaelSalguero** [comment]
Hi, that sounds great! Just try to make the code clean and using the same programming style as the whole project. Thanks

**Comment by labarilem** [comment]
Actually it seems like this extension is not able to correctly convert C# snippets that do not contain a class definition (e.g. a snippet containing only a method definition) 😢 
This is my main use case, so I might need to look into another extension.

**Comment by RafaelSalguero** [comment]
Can you post an example of such snipped, maybe we can do something :) Thanks.

**Comment by labarilem** [comment]
Okay, I'll open a new issue then.
