### ISSUE TITLE
Add option for "TrimEnd" characters

### ISSUE THREAD

**Issue by KerryRitter** [RafaelSalguero/CSharp2TS#4]
A lot of the C# POCOs I am converting end with "Dto" (some use ViewModel, etc). Adding a setting to enter in a string that will be trimmed off the end of any class name would be quite nice. I.e.

```
{
 "csharp2ts.trimEnd": "dto"
}
```

Which will convert `ProjectVersionDto` to `ProjectVersion`.

**Comment by RafaelSalguero** [comment]
I was already thinking on added support for a configuration file in which I could add more options in the future. This seems great as the first option for that file.
